language: ruby
before_install: gem install bundler -v="1.17"
script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
rvm:
  - 2.6.5
gemfile:
  - gemfiles/rails_52.gemfile
env:
  - RAILS_ENV=test
#notifications:
#  email: false
